### PR TITLE
Uncomment resetState $this->timeEllapsed = 0

### PR DESCRIPTION
**Pull request by g4b1nagy**
I'm still trying to figure out the second part of this issue.

### CODE REVIEW

**Comment by g4b1nagy** [comment]
#55

**Comment by shouze** [comment]
Yes you should change the version requirement for the tolerance dependency in composer.json file. It's because of a bug in this dependency that need to be fixed.

**Comment by tyx** [comment]
Just to let you know, tolerance 0.4.0 is not release yet !

**Comment by shouze** [comment]
@g4b1nagy yes, it's related to https://github.com/Tolerance/Tolerance/pull/67#issuecomment-256856215

**Comment by g4b1nagy** [comment]
I think I bit off more than I can chew right now. My bad. I'm closing the pull request.

**Pull request closed without merging**
