### PR TITLE
:ambulance: Ensure context isolation for each request

### PR DESCRIPTION
**Pull request by tyx**
If we want to let people use the same instance of RestApiBrowser to perform
different type of request with different context (Auth and no Auth for example)

Drawbacks:
* BC break as some people could use this **feature** to declare header once. 

One solution could be to move headers storage inside RestContext. So people could use restApiBrowser by passing directly headers to `sendRequest`. Still BC break but with less impact ?

### CODE REVIEW

**Comment by shouze** [comment]
Yes for sandRequest, in fact I guess most of the time headers should be stateless. The only case when we want to keep a state of headers is thing like auth token, we made the error to believe that the exception was the rule so in any cases we should be BC break about.

**Comment by tyx** [comment]
PR updated to reflect these changes.

Need to test with real app to see impact

**Comment by shouze** [comment]
LGTM. We need to test in real situation indeed.

**Comment by bangpound** [comment]
The current behavior where headers persist for the entire lifetime of a test suite came from the removal of the line which emptied this the `requestHeaders` array in `RestApiBrowser`.

https://github.com/rezzza/rest-api-behat-extension/commit/2b10927c10e2eb531480c427a4750413823d0fab#diff-9d1a35b8dac9c540c2aedf7c51d8e7e7L135

Without patching this class to restore the original behavior where the headers were reset after the request was sent, our test suite is completely nonfunctional.

**Comment by tyx** [comment]
We can close here. The fix in #70 is just enough to handle the behavior needed

**Pull request closed without merging**
