### PR TITLE
Add status to print request and response

### PR DESCRIPTION
**Pull request by lfbn**
I think is useful to have the status code of the response printed out.

### CODE REVIEW

**Comment by tyx** [comment]
Thanks !

Is it possible to have a screenshot before/after ?

**Comment by lfbn** [comment]
Yes. I've added after the method.

Before: http://imgur.com/WhyTDNT

After: http://imgur.com/dj5PVCI

**Comment by tyx** [comment]
Ok,

I feat that people have difficulties to understand this number or even see it. 

What about write it on a new line combinate to its description with `$response->getReasonPhrase()` ?

Will look
```
GET /my/url
200 OK
Header: value
```

**Comment by stephpy** [comment]
`delete 400` looks like an apache row. Not easy to read.

@tyx solution is more readable. :+1:

**Comment by lfbn** [comment]
Yeah. Seems good. What about this:

[image: Imagem intercalada 1]

2016-02-24 17:17 GMT+00:00 Stéphane PY <notifications@github.com>:

**Comment by lfbn** [comment]
Yeah. Seems good. What about this:

**Comment by stephpy** [comment]
Looks perfect to me.

**Comment by tyx** [comment]
:+1:

**Comment by shouze** [comment]
@lfbn looks great! can you plz squash into a single commit? Then will be good to merge.

**Comment by lfbn** [comment]
Hi @shouze, did I done the squash correctly? Thanks!

**Comment by shouze** [comment]
@lfbn :+1: good to merge!

**Comment by shouze** [comment]
@lfbn I've released https://github.com/rezzza/rest-api-behat-extension/releases/tag/3.1.2

**Pull request merged**
